---
title: "Math115 assign4"
author: "Vincent"
date: "2023-02-08"
output: pdf_document
---

From Section 1.5: exercise 1 parts (b), (d), (e); exercise 2 parts (a), (b), (c); exercises 7, 16, 18, 20. 

From Section 1.6: exercise 1 parts (a) through (g); exercise 2 part (a); exercise 3 part (a); exercises 4, 5, 11, 12, 15, 31. 

# 1.5

 **1. Label the following statements as true or false.**\newline\newline
  b) Any set containing the zero vector is linearly dependent. **False**\newline
  d) Subsets of linearly dependent sets are linearly dependent. **False**\newline
  e) Subsets of linearly independent sets are linearly independent. **True**\newline\newline
  
 **2. Determine whether the following sets are linearly dependent or linearly independent.**\newline\newline
  a) Linearly dependent, $c_1=1,c_2 = -2$\newline
  b) Linearly independent\newline
  c) Linearly independent\newline\newline
  
  **7. Recall from Example 3 in Section 1.3 that the set of diagonal matrices in $M_{2\times2}(F)$ is a subspace. Find a linearly independent set that generates this subspace.**\newline\newline
  As long as the diagonal matrices is a $m\times n$ zero matrices the set can generate this subspace is $S=${$0$}
  
  **16. Prove that a set S of vectors is linearly independent if and only if each finite subset of S is linearly independent.**\newline\newline
  **Proof: ** Recall that the subset of a linear independent set will be independent. So we can say that any random subset $S'\in S$ is linear independent iff S is linear independent. Therefore, when all of the S' in S are linear independent we will have S, the original set, is linear independent.\newline\newline
  
  **18. Let S be a set of nonzero polynomials in P(F) such that no two have the same degree. Prove that S is linearly independent.**\newline\newline
  *Proof: *$S\in P(F)$, $S=${$1,X,X^2,X^3....X^n$} where S contains n elements. We want say that $cS=${$c_0+c_1X+c_2X^2+...c_nX_n$}$=0$. There are no two element have the same degree, then the only way is set $c_0=c_1=c_2=...=c_n=0$. Therefore, S is linear independent.\newline\newline
  
  **20. Let $f,g\in F(R,R)$ be the function defined by $f(t)=e^{rt}$ and $g(t)=e^{st}$ where $r\ne s$. Prove that f and g are linearly independent in $F(R,R)$**\newline\newline
  
  *Proof: * Base on the implementation of f and g, we know that f and g will never have the same degree unless t equal to zero. Then if we want compute $f+g=0$ we must have that $t=0$. Therefore, f and g are linearly independent in $F(R,R)$\newline\newline
  
# 1.6

  **1. Label the following statements as true or false.**\newline\newline
  
   **(a) The zero vector space has no basis.**\newline
    False\newline
   **(b) Every vector space that is generated by a finite set has a basis.**\newline
    True\newline
   **(c) Every vector space has a finite basis.**\newline
    False\newline
   **(d) A vector space cannot have more than one basis.**\newline
    False\newline
   **(e) If a vector space has a finite basis, then the number of vectors in every basis is the same.**\newline
    True\newline
   **(f) The dimension of $P_n(F)$ is n**\newline
    False\newline
   **(g) The dimension of $M_{m\times n}(F)$ is m+n**\newline
    False\newline\newline
    
  **2. Determine which of the following sets are bases for $R^3$**\newline\newline
    a) $c_1(1,0,-1)+c_2(2,5,1)+c_3(0,-4,3)=(0,0,0)$ $c_1+2c_2=0, 5c_2-4c_3=0,-c_1+c_2+3c_3=0$, Then the only way to have all three statement equal is to have $c_1=c_2=c_3=0$\newline\newline
    
  **3. Determine which of the following sets are bases for $P_2(R)$**\newline\newline
    a) $c_1(-1,-1,2)+c_2(2,1,-2)+c_3(1,-2,4)=0$ and $-c_1+2c_2+c_3=0,-c_1+c_2-2c_3=0,2c_1-2c_2+4c_3=0$, we can have that $c_1=7,c_2=-3,c_3=1$ Then it is not a basis of $P_2(R)$\newline\newline
    
  **4. Do the polynomials $x^3-2x^2+1,4x^2-x+3$ and $3x-2$ generate $P_3(R)$? Justify your answer**\newline\newline
  $dim(P_3(R))=4$, then the number of element in the basis need to be 4. Therefore, its not.\newline\newline
  
  **5. Is {$(1,4,-6),(1,5,8),(2,1,1),(0,1,0)$} a linear independent subset of $R^3$? Justify your answer**\newline\newline
  $dim(R^3)=3$, However the number of element in the subset is 4. Therefore, its not.\newline\newline
  
  **11. Let u and v be distinct vectors of a vector space V. Show that if {u, v} is a basis for V and a and b are nonzero scalars, then both {$u+v,au$} and {$au,bv$} are also bases for V.**\newline\newline
  
  1) $c_1(u+v)+c_2(au)=0$ we can have that $c_1u+c_1v+c_2au=(c_1+ac_2)u+c_1v=0$ Then we can say that $c_1+ac_2=0,c_1=0$ or $c_1=c_2=0$ Therefore, {$u+v,au$} is linear independent\newline
  2) $c_1(au)+c_2(bv)=ac_1u+bc_2v=0$ We can have that $ac_1=0$ and $bc_2=0$. Therefore, linear independent for {$au,bv$}\newline 
  and if {u, v} is a basis for V and a and b are nonzero scalars, then both {$u+v,au$} and {$au,bv$} are also bases for V.\newline\newline
  
  **12. Let u, v, and w be distinct vectors of a vector space V. Show that if {u, v, w} is a basis for V, then {$u+v+w,v+w,w$} is also a basis for V**\newline\newline
  **Proof: ** $a(u+v+w)+b(v+w)+c(w)=au+(a+b)v+(a+b+c)w=0$ and we can conclude that $a=b=c=0$ Therefore, if {u, v, w} is a basis for V, then {$u+v+w,v+w,w$} is also a basis for V.
  
  **15. The set of all $n\times n$ matrices having trace equal to zero is a subspace W of $M_{n\times n}(F)$ (see Example 4 of Section 1.3). Find a basis for W. What is the dimension of W?**
  **Proof: ** A basis for the set of all $n\times n$ matrices with trace equal to zero is given by the matrices {$E_ij$}, where $E_ij$ is a matrix with 1 in the (i, j)th position and 0 elsewhere, for $i \ne j$. This set has $n(n-1)$ matrices, so it has dimension n(n-1), i.e. The dimension of W is n(n-1).\newline\newline

  **31. Let $W_1$ and $W_2$ be subspace of a vector space V having dimensions m and n, respectively, where $m\ge n$**\newline\newline
  **a) Prove that $dim(W_1\cap W_2) \ge n$**\newline\newline
  **Proof: **To prove that the dimension of the intersection of two subspaces $W_1$ and $W_2$ is greater than or equal to n, we use the fact that the dimension of a subspace is equal to the number of linearly independent vectors in a basis for that subspace.\newline
Since $W_1$ and $W_2$ are subspaces of V, they each have a basis with m and n linearly independent vectors, respectively. When we take the intersection of $W_1$ and $W_2$, we are left with a set of vectors that are in both $W_1$ and $W_2$. This set also forms a basis for $W_1\cap W_2$, and since it is a subset of the basis for $W_1$ and $W_2$, it must contain at least n linearly independent vectors.\newline
Therefore, $dim(W1\cap W2) \ge n$.
  
  **b) Prove that $dim(W_1+ W_2) \ge m+n$**\newline\newline
  **Proof: ** Since $dim(W_1) = m$ and $dim(W_2) = n$, there exist bases {$v1, v2, ..., vm$} for $W_1$ and {$u_1, u_2, ..., u_n$} for $W_2$.\newline
  Then we can have $dim(W_1+W_2)=dim(W_1)+dim(W_2)-dim(W_1\cap W_2)=m+n-dim(W_1\cap W_2),dim(W_1\cap W_2)> 0$ Therefore, $dim(W_1+ W_2) \ge m+n$


  
  
  
  
  