---
title: "Math115A 1/30 notes"
author: "Vincent"
date: "2023-01-30"
output: pdf_document
---

Recall that on Friday we proved the following\newline
**"Replacement Theorem"**\newline

Let V be a vector space. Let $G\subset V, L\subset V$ be finite subsets of V such that:\newline
a) G has n vectors & it generates V\newline
b) L has m vectors and is linearly independent.\newline
The $m\le n$ and there exists a subset $H\subset G$ with $n-m$ vectors such that $L\cup H$ generate V.\newline\newline
Recall also that we introduced the following important concept\newline

**Definition: **A subset S of a vector space V that's linearly independent and generates V is called a basis of the vector space V\newline
Today we'll use the replacement Theom and the concept of basis of a vector space V to introduce the notion of dimension of vector space V\newline\newline

## **9.1 Corollary**

Let V be a vector space having a finite basis (i.e. $\exists$ subset $S\subset V$ with S finite, linear independent and generating/spanning V)\newline
Then any other basis for V contains the some number of vectors\newline
**Proof: **\newline
Let $S'\subset V$ be another basis for V, i.e. S' linear independent and $span(S')=V$\newline
Denote by n the number of vectors in S. Assume $S'$ contains $n'$ vectors, with $n'>n$. Since $S'$ is linearly independent and $span(S)=V$, the replacement theom tells us that $n'\le n$.\newline
Thus, $S'$ must be finite and the number $n'$ of elements in $S'$ must be $n'\le n$.\newline 
Reversing the role of $S,S'$(which are both basis for V!) we obtain $n\le n'$ as well, thus $n'= n$\newline\newline

The above corollary stats that if a vector space V has a finite basis, then the number of elements in that basis is an imtrihisic property of V. Thus allocating hte following:\newline\newline

## **9.2 Definition**

A vector space V is said to be finite dimensional if it has a basis consisting of a finite number of elements. The unique integer n (confirm for 9.1!) such that any basis of V has exactly n elements is called the dimension of V, denoted $dim(V)$.\newline
A vector space that does not have a finite basis is called infinite dimensional.\newline\newline

## **9.3 Examples**\newline

1) The vector space {$0$} consisting of just the 0 vector has dimension 0, $dim(${$0$}$)=0$.\newline
2) $dim(R^n)=n$, more generally if F is an arbitary field, then $dim(F^n)=n$.\newline
Indeed, we have shown that the set of vector $S=${$(1,0,...,0),(0,1,0,...,0),...,(0,0,...,0,1)$} is linearly independent is $F^n$ and it generates $F^n$, so it is a basis, and we see S has exactly n vectors\newline
3) $dim(M_{m\times n}(F))=mn$ because $E_{ij}=\begin{pmatrix}0&0\\0&0\end{pmatrix}\in M_{m\times n}(F)$ are linear independent & generate $M_{m\times n}(F)$ so it is a basis, and it has $m\times n$ vectors\newline
4) The vector space $V=F[X]$ of all polynomials with coefficients in a field F is infinite-dimensional\newline\newline
Indeed, we know that $S=${$1,X,X^2,...$} are linearly independent if V would be finite dimensional, then it can be generated by a finite set of n elements and so by replacement Theom it would follow that any finite subset of S has $\le n$ many elements, te=hus S would be finite, contradiction. (because S has infinite many vectors.)\newline\newline

## **9.4 Exercise**

Do the polynomials $P_1=x^3-2x^2+1,P_2=3x-2,P_3=4x^2-x+3$ in $V=P_3(\mathbb{R})$(i.e. the vector space of all polynomials of degree $\le 3$ with coefficients in $\mathbb{R}$). generate $P_3(\mathbb{R})$?\newline
**Solution** No, they don't. Because the vector space $P_3(\mathbb{R})$ has the polynomials $1,X,X^2,X^3\in P_3(\mathbb R)$ which are linearly independent & span V. Thus, by replacement Theom, any basis for $P_3(\mathbb R)$ must have exactly 4 vectors in it, and {$P_1,P_2,P_3$} has any 3 vectors.\newline\newline

## **9.5 Exercise**

is the set $S=${$(1,4,-6),(1,5,8),(2,1,1),(0,1,0)$}$\subset \mathbb R^3$ a linear independent subset of $\mathbb R^3$\newline
**Solution**: No because by Replacement Theom, if $S\subset V$ linearly independent anad has n elements then $n\le dim(V)$ But $dim(V)=3$, and $4>3$ contradiction\newline\newline

Related to the above exercises, let us repeat are more time that conditions in the replacement theom and Corollary 9.1:\newline
if a vector space V is spanned (generated) by a subset of n vectors, then $dim(V)\le n$ and if are takes any set S of linearly independent vectors in V has $\le n$ many elements in it, i.e. if # elements in S is m, then $m\le n$\newline
Another consequence of the these results is that if $S\subset V$ is a set with m elements and $m< dim(V)$ then S cannot generate V, in particular S cannot be a basis for V.\newline\newline

##**9.6 Exercise**\newline

Let $W_1,W_2$ be subspaces of the vector space V and assume $dim(W_1)=m,dim(W_2)=n$. Where $m,n$ are finite integers.\newline
Prove that $dim(W_1+W_2)\le m+n$. $W_1+W_2=${$x+y:x\in W_1,y\in W_2$}\newline
**Solution: ** By the definition of dimension, the assumptions imply that there exist sets $S_1=${$v_1,...,v_m$}$\subset W_1$ and $S_12=${$v_1,...,v_m$}$\subset W_2$ such that:\newline
$S_1$ is linear independent & $span(S_1)=W_1$\newline
$S_2$ is linear independent & $span(S_2)=W_2$\newline
(i.e., $S_1$ is a basis for $W_1$, $S_2$ is a basis for $W_2$)\newline
But then $span(S_1\cup S_2)=span(S_1)+span(S_2)=W_1+W_2$\newline
Thus, by replace Theom, since $S_1\cup S_2$ has at most $m+n$ elements, we have $m+n\ge dim(W_1+W_2)$\newline\newline

## **9.7 Exercise**\newline
Let V be the subset of $M_{m\times n}(F)$ upper triangular\newline
i.e. $A=\begin{pmatrix}0&-&-\\0&0&-\\0&0&0\end{pmatrix}=(A_{ij})_j$ then $A_{ij}=0,,\forall i<j$\newline
Show that V vector subspace of $M_{m\times n}(F)$ find a basis and calculate $dim(V)$\newline
**Solution: ** First note that the set S of all matrices $E_{ij}=\begin{pmatrix}0&0&0\\0&1&0\\0&0&0\end{pmatrix}=(A_{ij})_j$ having 1 on entry ij. and all the other entries $=0$, with $j=i$ is a basis for V\newline
Indeed, we already show that $E=${$E_{ij}: 1\le j, j\le m$} is a linear independent and space the entrie vector space $M_{m\times n}(F)$ Thus, its subset S is still linearly independent, and it clearly space V.\newline
To count the number of elements in S note there are $n^2$ many elements in the large set E, form which we substract the number of matrices $E_{ij}$ in E that have some entry $ij$ equal to 1 under the diagnal\newline





