---
title: "Math115A 1/18 notes"
author: "Vincent"
date: "2023-01-19"
output: pdf_document
---

Recall from last time:\newline
**Definition**:\newline
A vector space (or a linear space) over a field F is a set V on which two operations are defined, called addition and scalar multiplication, so that for each $x,y\in V$ we gave a unique element $x+y\in V$(x plus y) and for each $x\in V$, $a\in F$ we have a unique element $ax \in V$ (a times x) such that the following conditions are satisfied:\newline\newline
**VS1** $x+y =y+x$, $\forall x,y\in V$ (commutative if addition)\newline
**VS2** $(x+y)+z=x+(y+z)$ ,$\forall x,y\in z\in V$(association of addition)\newline
**VS3** There exists an element in V denoted 0 such that $x+0=x, \forall x\in V$(the zero or neutral element in V)\newline
**VS4** For each $x\in V$ there exists $y\in V$ such that $x+y=0$ (the additive inverse in V, or opposite of x)\newline
**VS5** For each $x\in V$, we have $1x=x$\newline
**VS6** For each $a,b\in F, x\in V$, we have $(ab)x = a(bx)$\newline
**VS7** For each $a\in F$ and $x,y\in V$ we have $a(x+y)=ax+ay$\newline
**VS8** For each $a,b\in F$ and $x\in V$ we have $(a+b)x = ax+by$\newline\newline
The most common case of field determined by us will be $F=\mathbb{R}$(the field of real numbers with its usual + and * operations)

## 4.1 Example\newline
Given a field F and some $n>1$ the set of all n-tuples $v=(v_1,....v_n)$ with entries $v_1,....v_n \in F$ is denoted $F^n$. it is a vector space over F with respect to the operations + of addition "coordinate by coordinate". if $v=(v_1,....v_n), u=(u_1,...,u_n)$ then $v+u=(v_1+u_1,v_2+u_2....,v_n+u_n)$ and scalar multiplication $a(v_1,....,v_n)= (av_1,av_2,...,av_n)\in F^n$\newline
it is immediate to check that VS1-8 are all satisfied, as a consequence of the properties satisfied by + and * in the field F.\newline
Take for instance $F=\mathbb{R}$ and $n=3$, then $v=(-1,2,-4), u=(\frac{1}{2},-1,3)\in R^3=V$ and we have $v+u=(-1,2,-4)+(\frac{1}{2},-1,3)=(-\frac{1}{2},1,-1)$. Also, if $a=-1$ then $av=(1,-2,4)$

## 4.2 Example\newline
if F is a field and $m,n \geq 1$ integers, then the set of all $m \times n$ matrices over F, denoted $M_{m\times n}(F)$, is a vector space over F with respect to the following operations of addition and scalar multiplication:\newline
if $A,B\in M_{m\times n}(F)$ have entries\newline

$A=\begin{pmatrix}A_{11} & A_{12} &...&A_{1n}\\A_{21} & A_{22} &...&A_{2n}\\| &   &  &|\\A_{m1} & A_{m2} &...&A_{mn}\end{pmatrix}$\newline
$B=\begin{pmatrix}B_{11} & B_{12} &...&B_{1n}\\B_{21} & B_{22} &...&B_{2n}\\| &   &  &|\\B_{m1} & B_{m2} &...&B_{mn}\end{pmatrix}$\newline
then\newline
$A+B=\begin{pmatrix}A_{11}+B_{11} & A_{12}+B_{12} &...&A_{1n}+B_{1n}\\A_{21}+B_{21} & A_{22}+B_{22} &...&A_{2n}+B_{2n}\\| &   &  &|\\A_{m1}+B_{m1} & A_{m2}+B_{m2} &...&A_{mn}+B_{mn}\end{pmatrix}$\newline
and if $a\in F$ then\newline
$aA=\begin{pmatrix}aA_{11} & aA_{12} &...&aA_{1n}\\aA_{21} & aA_{22} &...&aA_{2n}\\| &   &  &|\\aA_{m1} & aA_{m2} &...&aA_{mn}\end{pmatrix}$\newline

For instance, take $F=\mathbb{R}$ abd $M_{2\times3}(\mathbb{R})$ the vector space of $2\times3$ matrices over $\mathbb{R}$\newline
$A=\begin{pmatrix}-1&2&3\\0&\frac{1}{2}&2\end{pmatrix}$\newline
$B=\begin{pmatrix}3&0&2\\0&\frac{1}{2}&-2\end{pmatrix}$\newline
then $A+B=\begin{pmatrix}2&2&1\\0&0&0\end{pmatrix}$\newline
The vector $0\in M_{2\times3}(R)$ is the $2\times3$ matrix with all entries=0\newline
$0=\begin{pmatrix}0&0&0\\0&0&0\end{pmatrix}$\newline\newline

##  4.3 Example\newline
if F is a field and S is a non-empty set, then we denote $F(S,F)$ the set of all functions $f:S\to F$ with domain S and codomain F, with addition given by:\newline
  if $f:S$ and $g:S\to F$ then $(f+g):S\to F$ is the function on S with values in F defined by $(f+g)(s)=f(s)+g(s)\in F$ and if $a\in F$ then scalar multiply by a is $af:S\to F$ defined by $(af)(s)=af(s)\in F$\newline
  **Remark** if we take $S={1,2,3,...,n}$ a finite set with $n\geq1$ elements, then $F([1,2,3,...n],F)$ is the same as $F^n$\newline\newline
  
## 4.4 Example\newline
A sequence with elements in F is a function $f:[1,2,....]\to F$ defined an real positive integers with values(codomain) in F if $f(n)=a_n\in F, n=1,2,....$ is an enumeration of the value of f then are also writes the sequence f as $(a_n)_n$\newline\newline
The set of sequences in F is a particular case of the Example 4.3 where $S=[1,2,...]$, and so it is a vector space V with respect to "entry by entry" addition of sequences and scalar multiplication given by:\newline
$(a_n)_n+(b_n)_n = (a_n+b_n)_n$ if $c\in F$ then $c(a_n)_n = (ca_n)_n$\newline\newline

## 4.5 Example\newline
Let $V=[(a_1,a_2):a_1,a_2\in \mathbb{R}]$ and for $(a_1,a_2),(b_1,b_2)\in V, c\in \mathbb{R}$ define:\newline
$(a_1+a_2)+(b_1+b_2)=(a_1+2b_1,a_2+3b_2)$\newline
$c(a_1,a_2)=(ca_1,ca_2)$\newline\newline
**Note: ** V as a set is the same as $\mathbb{R}$ but we modified the definition of + (but scalar multiplication is same as in $\mathbb{R}$)\newline
*Is V a vector space with this + and $\times$?*\newline
**No** because $+$ fails to satisfy VS1\newline
i.e. + as defined is not commutative $(a_1+a_2)+(b_1+b_2)=(a_1+2b_1,a_2+3b_2)$ while $(b_1+b_2)+(a_1+a_2)=(b_1+2a_1,b_2+3a_2)$\newline
For instance we take $(1,2)+(2,1)=(1+4,2+3)=(5,5)$ but $(2,1)+(1,2)=(2+2,1+6)=(4,7)$\newline
**Note** Also VS8 is not satisfied because $(1+1)(a_1,a_2)=(a_1,a_2)+(a_1,a_2)=(3a_1,4a_2)$ but $2(a_1,a_2)=(2a_1,2a_2)$\newline\newline

## 4.6 Theorem\newline
(cancellation rule for vector addition)\newline
if V is vector space over the field F and $x,y,z\in V$ so that $x+z=y+z$ then $x=y$\newline
**Proof:**\newline
By the axioms of $(V,+)$, there exist $v\in V$ such that $z+v=0$. Thus, we get that $x+z=y+z$ implies $(x+z)+v=(y+z)+v$ which by VS2 implies $x+(z+v)=y+(z+v)$ so $x+0=y+0$ which by VS3 implies $x=y$\newline\newline

## 4.7 Theorem\newline
Let V be vector space ever field F\newline
(a) The vector $0\in V$ is unique with the property VS3 i.e. if $0'\in V$ satisfies $x+0'=x, \forall x\in V$ then $0'=0$\newline\newline
(b) If $x\in V$ then there exists a unique $y\in V$ with $x+y=0$, i.e. if $y'\in V$ satisfies $x+y'=0$ then $y=y'$\newline 
**proof**\newline
(a) if 0' satisfies $x+0'=x, \forall x\in V$ then $0+0'=0$\newline
But by VS1 we have $0+0'=0'+0$ are by VS3 the element 0 satisfies itself the property $x+0=x,\forall x\in V$ which applied to $x=0'$ gives $0'+0=0'$. Thus\newline
$0+0'=0$ and $0'+0=0'$ so $0=0'$\newline
(b) if $x+y=0, x+y'=0$ then by VS1 we have $y+x=y'+x$ and by cancellation theom 4.6 thus implies $y=y'$\newline\newline

## 4.8 Theorem\newline
If V vector space over field F then we have\newline\newline
(a) $0x=0, \forall x\in V$\newline
(b) $(-a)x=-(ax)=a(-x),\forall x\in V, a\in F$\newline
(c) $a0=0, \forall a\in F$\newline
**Proof**\newline
(a) we have $0+0 =0$ so $0x=(0+0)x=0x+0x$ by cancellation rule $\to 0 = 0x$\newline
(b) $(-a)x+ax=0, -(ax)+ax=0, and a(-x)+ax=0$ Therefore, $ax$ is the inverse of $(-a)x$, $-(ax)$, and $a(-x)$, and $(-a)x=-(ax)=a(-x)$\newline
(c) $a0=a(0+0)=a0+a0$ so by theom 4.6 (cancellation law) 0= a0








