---
title: "Midterm 1 Review content"
author: "Vincent"
date: "2023-01-31"
output: pdf_document
---

De Morgan's law

X-(A$\cup$B) = (X-A)$\cap$(X-B)\newline
X-(A$\cap$B) = (X-A)$\cup$(X-B)\newline\newline


A function is a triple considering of:
  a set X called the domain of the function\newline
  a set Y called the codomain of the function\newline
  a rule of assigning to each element x$\in$X a unique element y$\in$Y
    (often this "rule" or "assignment" is given by a formula)\newline
We write such a triple f:X->Y with the y assigned x denoted f(x) or read it to x maps to f(x)
  (we often use the notation x$\mapsto$f(x) to emphesize that the function f assigns f(x) to x read it "x maps to f(x)")\newline
  

We say that a function is surjective when any y$\in$Y have a exist x$\in$X\newline
We say that a function is injective when any x$\in$X have a unique exist y$\in$Y\newline
We say that a function is bijective when any x$\in$X have a unique exist y$\in$Y and any y$\in$Y have a unique exist x$\in$X.\newline\newline

## 1.1 Field

A field F is a set on which one has two operations +, $*$, called addition and multiplication, are defined so that for each x,y $\in$ F corresponds a unique element in F denoted x+y and a unique element denoted $x * y$ such that the following properties are satisfied for all elements a, b, c $\in$F: \newline
(F1) $a+b = b+a$, $a*b=b*a$\newline\newline
(F2) $(a+b)+c =a+(b+c); (a*b)*c=a*(b*c)$\newline\newline
(F3) There exist distinct elements 0 and 1 in F such that 0+a=a and 1$*$a = a, $\forall$a $\in$F\newline\newline
(F4) For each a$\in$F and each b$\in$F, b!=0 there exist elements c$\in$F, d$\in$F such that a+c=0, b*d=1\newline\newline
(F5) $a*(b+c)=a*b+a*c$ distributivity of multiplication.\newline\newline

The element x+y called the sum of x&y x$*$y called the product of x&y\newline
The element 0 is called the identity element for addition\newline
The element 1 called the identity element for multiplication\newline
The element c in (F4) with property a + c = 0 called the addition inverse of a.\newline
The element d in (F4) with property a$*$d = 1 called the multiplication inverse of c\newline\newline\newline

let(F,+,$*$) be a field. For any a,b,c $\in$ F we have:\newline
 (1) if a+b =c+b Then a=c\newline
 (2) if a*b=c*b and b!=0, then a=c.\newline\newline
 
The element 0 and 1 in a field are unique. Also the additive inverse of an element and the multiplicative inverse of a != 0 element are unique\newline


## 1.2 Vector Space

Definition: A vector space V over a field F consists of a set V on which two operations(called addition and scalar multiplication) are defined, so that for each x,y $\in$V, we have a unique element x+y in V and for each x$\in$V and a$\in$F we have a unique element ax$\in$V(scalar) such that the following conditions hold:\newline
(VS1) x+y=y+x, $\forall$ x,y$\in$V\newline
(VS2) (x+y)+z=x+(y+z), $\forall$ x,y,z$\in$V\newline
(VS3) There exists on element in V denoted 0 such that x+0=x, $\forall$x$\in$V\newline
(VS4) For each x$\in$V have exist y$\in$V such that x+y=0\newline
(VS5) For each x$\in$V we have 1x=x\newline
(VS6) For each x$\in$V, a,b$\in$F we have (ab)x=a(bx)\newline
(VS7) For each x,y$\in$V, a$\in$F we have a(x+y) =ax+ay\newline
(VS8) For each x$\in$V, a,b$\in$F we have (a+b)x=ay+bx\newline

## 1.3 subspace

A subset W of a vector space V over a field F is called a subspace of V if W is a vector space over F with the operations of addition and scalar multiplication defined on V.\newline\newline

To check if a subset is under a Field:\newline
  (1) $0\in S$\newline
  (2) closure under addition, $x+y\in S, x, y\in S$
  (3) closure under multiplication, $cx\in S, x\in S, c\in F$
  
If $S_1,S_2$ are nonempty subsets of a vector space V then the sum of $S_1$ and $S_2$, denoted $S_1+S_2$ is the set {$x+y: x\in S_1, y\in S_2$}\newline\newline
Let $W_1, W_2$ be subspace of the vector space V. We say that V is the direct sum of $W_1$ and $W_2$ if $W_1\cap W_2=${0} and $W_1+W_2 =V,$ and we then write $V=W_1+W_2$\newline\newline
  
## 1.4 linear combination

Let V be a vector space over a field F and $S\in V$ a nonempty subset of V. A vector $v\in V$ is called a linear combination of vectors in S. If there exist a finite number of vectors $u_1,.....,u_n\in S$ and scalars $c_1,...,c_n\in F$ such that $v=c_1u_1+c_2u_2...+c_nu_n$\newline\newline

If V is a vector space and $S\ne 0\in V$, Then the span of S, denoted $span(S)$, is the set of all linear combinations of vectors in S.\newline
The span of any subset S of a vector space V is a subspace of V. Any subspace of V that contains S must contain $span(S)$\newline
The span of a subspace is always a subspace itself\newline

## 1.5 linear independent

A subset of vectors since vector space V is linearly dependent if there exist finitely many distinct vectors $v_1,..,v_n\in S$ and scalars $c_1,...,c_n\in F$ not all of there 0, such that $c_1v_1+c_2v_2+...+c_nv_n=0$\newline
In other word: if one can express the vector 0 as a linear combination of distinct vectors in S with non-zero coefficients.\newline\newline











